{"timestamp":"2025-10-26T07:23:25.401745Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-26T07:23:25.403590Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_dag_from_scripts.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-26T07:23:25.470627Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.471312Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.472062Z","level":"info","event":"Current task name:run_etl_process","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.472614Z","level":"info","event":"Dag name:etl_retail_transactions_dag","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.473301Z","level":"info","event":"Starting ETL Process","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.473720Z","level":"info","event":"Extracting data from source_db...","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.505601Z","level":"warning","event":"pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.","category":"UserWarning","filename":"/opt/airflow/dags/etl_dag_from_scripts.py","lineno":20,"logger":"py.warnings"}
{"timestamp":"2025-10-26T07:23:25.517427Z","level":"info","event":"[Extract] 3 rows extracted from source_db","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.518069Z","level":"info","event":"Transforming data (convert timestamps to UTC)...","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.520539Z","level":"info","event":"[Transform] 3 rows after transformation","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.521313Z","level":"info","event":"Loading data to warehouse_db with soft delete sync...","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.531959Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `postgres_warehouse` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/etl_dag_from_scripts.py","lineno":35,"name":"etl_process"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":234,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":243,"name":"connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py","lineno":61,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":228,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":218,"name":"_handle_connection_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-26T07:23:25.535107Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.535627Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.536064Z","level":"info","event":"Task:<Task(PythonOperator): run_etl_process>","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:23:25.536477Z","level":"info","event":"Failure caused by The conn_id `postgres_warehouse` isn't defined","logger":"task.stdout"}
