{"timestamp":"2025-10-25T12:25:57.906187Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-25T12:25:57.907931Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test_postgres_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-25T12:25:57.954777Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/test_postgres_dag.py","lineno":2,"logger":"py.warnings"}
{"timestamp":"2025-10-25T12:25:57.981307Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:57.981812Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:57.982291Z","level":"info","event":"Current task name:check_postgres_connection","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:57.982686Z","level":"info","event":"Dag name:test_postgres_dag","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:58.160695Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"host.docker.internal\" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user \"airflow\"\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/test_postgres_dag.py","lineno":14,"name":"test_postgres_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":281,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-25T12:25:58.162745Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:58.163531Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:58.164189Z","level":"info","event":"Task:<Task(PythonOperator): check_postgres_connection>","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:58.164663Z","level":"info","event":"Failure caused by connection to server at \"host.docker.internal\" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user \"airflow\"","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:25:58.165045Z","level":"info","event":"","logger":"task.stdout"}
