{"timestamp":"2025-10-25T12:21:54.778760Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-25T12:21:54.780479Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test_postgres_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-25T12:21:54.820948Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/test_postgres_dag.py","lineno":2,"logger":"py.warnings"}
{"timestamp":"2025-10-25T12:21:54.856977Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.857656Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.858306Z","level":"info","event":"Current task name:check_postgres_connection","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.858739Z","level":"info","event":"Dag name:test_postgres_dag","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.876043Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres\" (172.18.0.2), port 5432 failed: FATAL:  database \"source_db\" does not exist\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/test_postgres_dag.py","lineno":14,"name":"test_postgres_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":281,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-25T12:21:54.902788Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.903596Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.904286Z","level":"info","event":"Task:<Task(PythonOperator): check_postgres_connection>","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.904872Z","level":"info","event":"Failure caused by connection to server at \"postgres\" (172.18.0.2), port 5432 failed: FATAL:  database \"source_db\" does not exist","logger":"task.stdout"}
{"timestamp":"2025-10-25T12:21:54.905317Z","level":"info","event":"","logger":"task.stdout"}
